### ISSUE TITLE
How to add .klib as classpath dependencies

### ISSUE THREAD

**Issue by GuilhE** [ZacSweers/kotlin-compile-testing#304] opened 2024-11-26 15:13 UTC
Following the _Unresolved references #302_ , I’ve been investigating and found that not using KSP2 sets `kspWithCompilation = false`. This explains why the tests were working when using `tschuchortdev/kotlin-compile-testing`—the compilation step wasn’t actually happening.

To confirm, I tested with `tschuchortdev` and `kspWithCompilation = true`, as well as with your library (`useKsp2()` omitted), using `languageVersion = 1.9` and `kspWithCompilation = true`. Both cases failed as expected, showing consistent behavior.

Ultimately, both libraries seem to be functioning as expected. The issue now lies in adding the required dependencies to the classpath. Specifically, I need to resolve these imports:
```
import androidx.compose.ui.window.ComposeUIViewController
import platform.UIKit.UIViewController
```
It seems the dependencies are packaged in `.klib`  😬 files: 

![Screenshot 2024-11-26 at 13 13 55](https://github.com/user-attachments/assets/bb25eac3-5368-4009-8785-1a74a69a311a)
> ~/.gradle/caches/modules-2/files-2.1/org.jetbrains.compose.ui/ui-uikitsimarm64/1.7.1/6314e65b9b0f9dc7e0a5fdd70256def5ffb4377c/ui.klib!/default/linkdata/package_androidx.compose.ui.window/1_window.knm

![Screenshot 2024-11-26 at 13 14 18](https://github.com/user-attachments/assets/1c2b674a-e165-4b0a-bedb-53cafc413b87)
> ~/.konan/kotlin-native-prebuilt-macos-aarch64-2.1.0-RC2/klib/platform/ios_simulator_arm64/org.jetbrains.kotlin.native.platform.UIKit/default/linkdata/package_platform.UIKit/04_UIKit.knm

However, I can’t figure out how to add these `.klib` files to the classpath. I’ve tried adding the necessary plugins and dependencies in the module's `build.gradle`, as follows:
```
alias(libs.plugins.kotlin.compose)
alias(libs.plugins.kotlin.compose.compiler)
implementation(compose.runtime)
implementation(compose.ui)
```
Unfortunately, the compilation still fails with unresolved references in the generated files when attempting to compile for testing. 😞

Could you help me figure out how to correctly add these dependencies to the classpath? Thanks!

**Comment by ZacSweers** [comment] 2024-11-27 06:31
This is a dupe of #298

**Closed by ZacSweers** 2024-11-27 06:31 UTC

**Comment by GuilhE** [comment] 2024-11-27 10:25
I’m not sure if it’s a direct duplicate "as is," because I tested using `isMultiplatformCommonSource = true` and `kspWithCompilation = true` in the original library, and the unresolved references issue persists. If I bump the version to 2.0/2.1, it doesn’t even generate the files (regardless of the `kspWithCompilation` value). 

I believe the issue is that KMP is simply not supported. That said, since Google doesn’t provide a library to test KSP, we end up using this one to validate whether the files are generated as expected. In my case, since I need KMP support, I limit myself to checking if the generated files match my expectations and skip (or can’t) validating whether they compile.  

Thanks!

**Comment by ZacSweers** [comment] 2024-11-27 13:51
KMO is indeed not currently supported and that issue tracks that

**Comment by GuilhE** [comment] 2024-11-27 18:15
If anyone else ends up here with the same question, I found a [workaround](https://github.com/GuilhE/KMP-ComposeUIViewController/blob/c36b2b135169c692451a8b97bb12724a26441886/kmp-composeuiviewcontroller-ksp/src/test/kotlin/composeuiviewcontroller/TestUtils.kt#L55) that essentially involves creating the necessary file signatures in a way that satisfies the compiler. Now the compilation works.
