### ISSUE TITLE
resolver.getSymbolsWithAnnotation doesn't return all annotated symbols

### ISSUE THREAD

**Issue by tokazio** [ZacSweers/kotlin-compile-testing#285] opened 2024-09-09 20:11 UTC
I have a test case that was ok in kotlin 1.9.24 and compatible ksp and kotlin-compile-testing 

When upgrading to 2.0.20 (and the latest 0.5.1 from here) it's not ok anymore

Given a data class
```
data class TestData(
  @FilteredField(read = PermissionScope.PRIVATE)
  var name: String? = ""

  override var description: String? = "",

): TestInterface
```
and its interface
```
interface TestInterface {
    @FilteredField(read = PermissionScope.SECRET)
    var description: String?
}
```
Compiling like
```
val kotlinSourceData = SourceFile.fromPath("TestData.kt".fromResource())
val kotlinSourceInterface = SourceFile.fromPath("TestInterface.kt".fromResource())
KotlinCompilation().apply {
    sources = listOf(kotlinSourceData,kotlinSourceInterface)
    workingDir = temporaryFolder
    inheritClassPath = true
    jvmTarget = JvmTarget.JVM_17.description
    configureKsp(useKsp2 = true) {
      symbolProcessorProviders.add(FilteredFieldSymbolProvider())
      kspIncremental = true
      incrementalLog = true
      withCompilation = true
      loggingLevels = setOf(CompilerMessageSeverity.INFO)
    }
    kspIncremental = true
  }
    .compile()
```
I can see the 2 files in the compilation results but

The `description` property from the interface is not in the result list of `resolver.getSymbolsWithAnnotation("...FilteredField",false)`

**Comment by tokazio** [comment] 2024-09-09 21:10
seems to use a ResolverAAImpl from ksp 2.0.0-1.0.22

**Comment by ZacSweers** [comment] 2024-09-19 21:57
Please share a minimally reproducible sample project or failing test case in this repo, thanks!

**Comment by ZacSweers** [comment] 2024-09-19 21:58
Also see #257 in case

**Comment by tokazio** [comment] 2024-09-24 16:07
Yes using
```
val compilation = KotlinCompilation().apply {
  sources = sourceFiles
  configureKsp(useKsp2 = true) {
    withCompilation = true
    symbolProcessorProviders.add(...)
  }
}
```
is better but not sufficient

**Comment by ZacSweers** [comment] 2024-09-24 16:18
Sorry that's not a reproducible sample project or test. Going to have to insist on that or I'll need to close this issue.

**Comment by tokazio** [comment] 2024-09-25 09:46
yes i need to find some minutes to give you a sample

**Comment by ZacSweers** [comment] 2024-11-11 21:20
Closing due to lack of info

**Closed by ZacSweers** 2024-11-11 21:20 UTC

**Comment by tokazio** [comment] 2024-12-06 12:49
Found that my annotations were
```
@Target(AnnotationTarget.FIELD, AnnotationTarget.PROPERTY, AnnotationTarget.VALUE_PARAMETER)
```
And that @Target AnnotationTarget.VALUE_PARAMETER are filtered from KSAnnoted.annotations
